title: Um Lugar Sem Nome Com Nome.
author: Leone
subtitle: Acervos e Aleatoriedades

url: "https://parchment-agoraphobia.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://twitter.com/SchifosoLo"
footer_text: "Feito por Leone, Lo Schifoso"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Sobre"
   link: "sobre"

